In [1]:
import numpy as np

In [9]:
data = np.load('dataset.npz', allow_pickle=True)

In [4]:
data.files

['ingredients', 'recipes']

In [6]:
data['ingredients']

array(['salt', 'pepper', 'butter', ..., 'watercress leaves',
       'emerils essence', 'corn flakes cereal'], dtype='<U39')

In [10]:
data['recipes']

array([array([ 233, 2754,   42,  120,  560,  345,  150, 2081,   12,   21]),
       array([ 198,  249,    2,  194, 1884,  791,  965,  423,   53,   48,  798,
         31,  362, 1031,   94,   26,    8]),
       array([ 328,  263,   62,   46,  445,   55, 1196,   82,  664,    3,  602,
         10,    7,    6,    1,  128,   61,  141,    0,  262,  140,  655,
         21,    8,   23,   84]),
       ...,
       array([  72,  155, 1603,  402,    3,   79,  330,   76,    6, 1102,   60,
         44,   58]),
       array([ 28,   2, 247,  47,   0,   4, 348,   8]),
       array([  72,  208,   89,    2, 1491, 1725,   19,   64,   82,  202,  173,
          3,    9,  106,   42,   10,    7,   31,    1,  150,   70,  201,
         23,   84,  102])], dtype=object)